[package]
name = "may_minihttp"
version = "0.1.0"
edition = "2018"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
may = "0.3"
log = "0.4"
time = "0.1"
itoa = "0.4"
bytes = "0.4"
httparse = "1"
rcu_cell = "0.1"
lazy_static = "1"

[dev-dependencies]
markup = "0.4"
num_cpus = "1.0"
oorandom = "11"
smallvec = "0.6"
env_logger = "0.7"
v_htmlescape = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
may_postgres = { git = "https://github.com/Xudong-Huang/may_postgres.git" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
