[package]
name = "may_minihttp"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
bytes = "0.4"
httparse = "1"
log = "0.4"
time = "0.1"

[dev-dependencies]
env_logger = "0.4"
